version: "3.5"
services:
    pc-template-test:
      image: 192.168.1.252:5000/saas/${PROJECT_NAME}:${PROJECT_VERSION} # 需要修改PROJECT_VERSION变量名
      networks:
        - ii-swarm-net
      working_dir: /app
      tty: true
      stdin_open: true
      environment:
        - TZ=Asia/Shanghai
        - LANG=C.UTF-8
        - PROJECT_NAME=${PROJECT_NAME}
      restart: always
      deploy: # deploy下的配置,仅集群下生效
        mode: replicated # 副本模式
        replicas: 1 # 部署几个容器实例
        placement:
          constraints: # 部署节点限制
            - node.labels.roles == common # 此配置限制部署节点必须是demo节点
networks:
  ii-swarm-net:
    external: true

